version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  todo-api:
    build: ./todo-api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      SECRET_KEY_BASE: "rake secret"
    env_file:
      - .env
    ports:
      - "3003:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      todo-net:
  todo-app:
    build: ./todo
    env_file:
      - .env
    ports:
      - "2345:80"
    tty: true
    stdin_open: true
    networks:
      todo-net:
networks:
  todo-net:
    external: true
