version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  todo-api:
    container_name: todo-api
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: "rake secret"
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    networks:
      todo-net:
networks:
  todo-net:
    external: true
